package com.afriland.packageservices.enums;

import lombok.Getter;
import lombok.Setter;

public enum HTTPResponseMessage {

    RESOURCE_NOT_EXISTS("RESOURCE_NOT_EXISTS"),

    BAD_VALUE_FORMAT("BAD_VALUE_FORMAT"),

    BAD_PHONE_NUMBER_FORMAT("BAD_PHONE_NUMBER_FORMAT"),

    OBJECT_ALREADY_EXISTS("OBJECT_ALREADY_EXISTS"),
    OBJECT_DOES_NOT_EXISTS("OBJECT_DOES_NOT_EXISTS"),

    UNABLE_TO_DELETE_OBJECT("UNABLE_TO_DELETE_OBJECT"),

    OBJECT_SUCCESSFULLY_DELETED("OBJECT_SUCCESSFULLY_DELETED"),
    UNABLE_TO_PROCESS("UNABLE_TO_PROCESS"),

    SUBSCRIBED("subscribed"),

    SUCCESSFULLY_SUBSCRIBED("SUCCESSFULLY_SUBSCRIBED"),
    UNSUCCESSFULLY_SUBSCRIBED("UNSUCCESSFULLY_SUBSCRIBED"),

    BAD_ACCOUNT_NUMBER_FORMAT("BAD_ACCOUNT_NUMBER_FORMAT"),

    UNABLE_TO_GENERATE_OTP("UNABLE_TO_GENERATE_OTP"),
    UNABLE_TO_SEND_OTP("UNABLE_TO_SEND_OTP"),


    OTP_SUCCESSFULLY_SEND("OTP_SUCCESSFULLY_SEND"),


    MESSAGE("message"),

    STATUS("status"),


    ERROR("ERROR"),

    SUCCESS("SUCCESS");

    @Getter
    @Setter
    public String value;

    private HTTPResponseMessage(String value) {

        this.setValue(value);
    }

}
